lessons/delegation_and_role_deps/rolling_update.yml
the old way doesnt work with the current Ansible version.
=> Update to haproxy module syntax

lessons/custom_module/library/foo.py, lessons/custom_module/library/solution.py
Copied custom module solution foo to solution.py and turned foo.py into a stub students can use to bootstrap their work with.
=> Custom module workshop starter file

aws_lab_setup/roles/training_infra/defaults/main.yml, lessons/adhoc_examples/README.md, workshops/adhoc_commands/README.md, workshops/adhoc_commands/solution/adhoc_commands.txt, workshops/basic_playbook/README.md
These are a few bits that I've noticed from delivering training based on this repo.
=> A few minor updates

workshops/basic_playbook/solution/telegraf.yml
For consistency, fix deprecated use of bare variable in the telegraf.yml playbook
=> Fix deprecated use of bare variable in with_items

lessons/apache_playbook/site.yml
Correct things James commented on during SAP training.
=> Make playbook example more efficient

tools/aws_lab_setup/README.md
Added item to install passlib into the facilitator documentation. Task #88
=> Inserted passlib install into the facilitator README.md

tools/aws_lab_setup/roles/common/defaults/main.yml, tools/aws_lab_setup/roles/common/handlers/main.yml, tools/aws_lab_setup/roles/common/tasks/RedHat.yml
Added specific firewall rules for RHEL and made sure firewalld is running.
This should fix task #101 and #117
Tested by spinning up a lab and testing ping from the control node.
=> Made firewalld rules more specific for RHEL

tools/aws_lab_setup/README.md
I got stuck a little bit on the readme here, so I cleaned it up just a bit (this is super minor)
=> cleaning up AWS readme

tools/aws_lab_setup/roles/manage_ec2_instances/defaults/main.yml, tools/aws_lab_setup/roles/manage_ec2_instances/tasks/create.yml, tools/aws_lab_setup/roles/manage_ec2_instances/templates/instances.txt.j2
#130 Fixed this by modifying both the variable name from 'control' to 'ansible' and then made adjustments to logic for both tasks and jinja templating where applicable.
=> Modifed the hostname alias from 'control' to 'ansible' for issue #130

.travis.yml, examples/cloud-aws/README.md, facilitator/solutions/basic_playbook.md, facilitator/solutions/roles.md, facilitator/solutions/simple_playbook.md, facilitator/solutions/tower_install.md, tools/aws_lab_setup/README.md, workshops/ansible_install/README.md, workshops/tower_install/README.md
* Add Travis
* Fix remaining MD issues
* Reapply spelling corrections that got broken in a bad rebase
In `.travis.yml` I've left in, though disabled `ansible-lint`
=> Travis CI to validate Markdown

CONTRIBUTING.md
* Details on how to run markdown linter
* Link to Ansible Style Guide
* Multi-line YAML
* Correct use of lists
=> Coding Guidelines

decks/ansible-essentials.html, examples/apache-basic-playbook/site.yml, examples/apache-role/roles/apache-simple/handlers/main.yml, examples/apache-role/roles/apache-simple/tasks/main.yml, examples/apache-role/site.yml, examples/apache-simple-playbook/site.yml, examples/cloud-aws/provision.yml, examples/cloud-aws/setup.yml, examples/nginx-basic-playbook/site.yml, examples/nginx-remove-playbook/site.yml, examples/nginx-role/roles/nginx-simple/handlers/main.yml, examples/nginx-role/roles/nginx-simple/tasks/main.yml, examples/nginx-role/roles/nginx-simple/tasks/remove.yml, examples/nginx-role/site.yml, examples/nginx-simple-playbook/site.yml, guides/ansible_engine/2-playbook/README.md, guides/ansible_engine/3-variables/README.md, guides/ansible_engine/4-role/README.md, tools/aws_lab_setup/roles/common/handlers/main.yml
So I noticed most of the tasks are lowercase, and are not actual
sentences. Start-case is preferred as the gather_facts phase also
displays "Gather Facts" (unfortunately this is Title-case)
I also made sentences out of it (mostly adding 'Ensure ...')
And notification handlers are Start-hyphen-case.
=> Ensure all names are Title-case

tools/aws_lab_setup/roles/common/handlers/main.yml, tools/aws_lab_setup/roles/common/tasks/main.yml
=> Update handler and notification names to be consistent

decks/ansible-essentials.html
Either Restart or restart.
Pushing as 'restart' with lowercase r
=> handler names should match

guides/ansible_engine/3-variables/README.md, guides/ansible_engine/4-role/README.md, guides/ansible_tower/2-config/README.md
There is no inventory file named inventory.ini so it should be removed from ansible-playbook cmdline
=> fixed some typos in guided exercises

decks/ansible-best-practices.html
Ansible Best Practices: The Essentials
* Based on Tim's presentation
* Common presentation, so lets get it in a common location
* Tweak intro (imports and first slide) to match existing presentations
**Work needed**
**Notes for reviewers**
* Based on https://github.com/ansible/lightbulb/pull/193
* Commit one is Tim's original work, so for reviewing you may wish to step through from commit two onwards
=> Deck: Ansible Best Practices: The Essentials

decks/ansible-best-practices.html
@rndmh3ro Thanks for pointing this out
I've left in the speaker notes for questions as I think they can help get some audience participation.
=> Remove who am I fixes: #58

guides/ansible_engine/3-variables/README.md
sitting in your workshop - found this typo - fixing it up
=> fix typo - handlers not handler

decks/ansible-essentials.html
We just found a bug with the handler and some minor naming issues.
=> minor fixes for the handler part of the slidedeck

decks/your_first_pb.html
This deck was presented at Ansible Fest and can be used/made better and given at community meetups.
=> Your First Playbook Deck

decks/contributing-to-ansible.html, index.html
You can view them at https://gundalow-lightbulb.netlify.com/decks/contributing-to-ansible.html#/
=> [WIP] Deck: Contributing to Ansible
